import {
  CpuIcon,
  TerminalWindowIcon,
  MusicNotesIcon,
  BugIcon,
  LightningIcon,
  GlobeIcon,
  ShieldIcon,
  KeyboardIcon,
  DatabaseIcon,
  CloudIcon,
  CodeIcon,
  ShareNetworkIcon,
  GitMergeIcon,
  ComputerTowerIcon,
  LockIcon,
  BracketsCurlyIcon,
  GameControllerIcon,
  BookIcon,
  GithubLogoIcon,
  LinkedinLogoIcon,
  EnvelopeIcon,
  TwitterLogoIcon,
  GraduationCapIcon,
} from '@phosphor-icons/react';

export const aboutData = {
  profile: {
    name: "Ahmed Samil Bulbul",
    role: "Senior Software Engineer",
    tagline: "turning complex ~distributed~ problems into elegant, reliable code.",
    location: "Ankara, Türkiye",
    email: "samil.bulbul@gmail.com",
    avatar: "/images/herdaim.jpg",
    links: [
      { label: "GitHub", url: "https://github.com/fezcode", icon: GithubLogoIcon },
      { label: "LinkedIn", url: "https://www.linkedin.com/in/ahmedsamilbulbul", icon: LinkedinLogoIcon },
      { label: "Email", url: "mailto:samil.bulbul@gmail.com", icon: EnvelopeIcon },
      { label: "Twitter", url: "https://x.com/fezcoddy", icon: TwitterLogoIcon },
      { label: "Fezcode", url: "https://fezcode.com", icon: GlobeIcon },
    ]
  },
  stats: [
    { label: "Experience", value: "8+", unit: "Years" },
    { label: "Systems Architected", value: "Critical", unit: "Scale" },
    { label: "Valedictorian", value: "3.89", unit: "GPA" },
  ],
  skills: [
    { name: "Go (Golang)", level: 98, icon: CpuIcon, type: "language" },
    { name: "System Design", level: 91, icon: GlobeIcon, type: "core" },
    { name: "Kubernetes & Cloud", level: 92, icon: CloudIcon, type: "devops" },
    { name: "Distributed Systems", level: 90, icon: ShareNetworkIcon, type: "core" },
    { name: "Node.js & Express.js", level: 88, icon: ComputerTowerIcon, type: "backend" },
    { name: "C++ & C", level: 85, icon: CodeIcon, type: "language" },
    { name: "PostgreSQL & Mongo", level: 88, icon: DatabaseIcon, type: "backend" },
    { name: "React & JS", level: 82, icon: BracketsCurlyIcon, type: "frontend" },
    { name: "Rust", level: 75, icon: LockIcon, type: "language" },
    { name: "CI/CD & DevOps", level: 88, icon: GitMergeIcon, type: "devops" },
  ],
  experience: [
    {
      company: "Picus Security",
      role: "Senior Software Engineer",
      period: "Oct 2022 - Sep 2025",
      desc: "Led flagship Exposure Validation (EXV) product development. Architected Cloud Security Validation (CSV) from scratch. Migrated PostgreSQL to MongoDB, reducing query times from 2 hours to under 5 minutes.",
      type: "Cybersecurity",
    },
    {
      company: "Aselsan - Smart Cities",
      role: "Senior Software Engineer",
      period: "Jan 2021 - Oct 2022",
      desc: "Engineered Node-RED workflow platform scalability on K8s. Developed core NPM packages for low-code solutions. Built web-based deployment platform abstracting K8s complexity.",
      type: "IoT / Big Data",
    },
    {
      company: "Aselsan - Toll Collection",
      role: "Software Engineer & DevOps",
      period: "Jan 2018 - Jan 2021",
      desc: "Refactored monolithic C++98 to C++17 microservices with gRPC. Reduced container sizes from 168MB to 8MB. Implemented air-gapped Nexus Repository Manager.",
      type: "Critical Infra",
    },
  ],
  traits: {
    education: {
      title: "Valedictorian",
      desc: "Hacettepe University, BSc in Computer Science. GPA: 3.89/4.0. Coursework: Algorithms, Parallel Processing, Computer Networks.",
      icon: GraduationCapIcon,
    },
    superpower: {
      title: "The Optimizer",
      desc: "Reduced query times from 2 hours to 5 minutes. Shrunk container images by 95%. Optimization is not a task, it's a lifestyle.",
      icon: LightningIcon,
    },
    warStory: {
      title: "The Monolith Breaker",
      desc: "Refactored a massive legacy C++98 monolith into a modern, containerized C++17 microservices architecture using gRPC and Docker.",
      icon: ShieldIcon,
    },
    kryptonite: {
      title: "Manual Deployments",
      desc: "If it's not automated, it's wrong. I will build a CI/CD pipeline for a Hello World app if I have to.",
      icon: BugIcon,
    },
    hobby: {
      title: "Sonic Alchemist",
      desc: "Creating beats and melodies. Exploring the intersection of code and sound in music production.",
      icon: MusicNotesIcon,
    },
    tool: {
      title: "Mechanical Keys",
      desc: "Loved mechanical keyboards. Thock, clack, and tactile perfection.",
      icon: KeyboardIcon,
    },
    gaming: {
      title: "Narrative Grooving",
      desc: "Vibing with story-driven games. Letting the plot beats drop and the character arcs flow.",
      icon: GameControllerIcon,
    }
  },
};
