import {
  CompassIcon,
  TerminalWindowIcon,
  PaintBrushIcon,
  GameControllerIcon,
  ColumnsIcon,
  SunglassesIcon,
  UserIcon,
  LightningIcon,
  SkullIcon,
  BookOpenIcon,
  BookBookmarkIcon,
  BooksIcon,
  GhostIcon,
  EyeSlashIcon,
  ChalkboardIcon,
  CastleTurretIcon,
  MartiniIcon,
  TimerIcon,
  LogIcon,
  KanbanIcon
} from '@phosphor-icons/react';

export const ACHIEVEMENTS = [
  {
    id: 'hello_world',
    title: 'Hello World',
    description: 'Welcome to Fezcodex.',
    icon: <CompassIcon size={32} weight="duotone" />,
    category: 'Exploration',
  },
  {
    id: 'curious_soul',
    title: 'Curious Soul',
    description: 'Visited the About Me page to learn who is behind this.',
    icon: <UserIcon size={32} weight="duotone" />,
    category: 'Exploration',
  },
  {
    id: 'story_explorer',
    title: 'Story Explorer',
    description: 'Did you hear about the Serfs?',
    icon: <BookOpenIcon size={32} weight="duotone" />,
    category: 'Exploration',
  },
  {
    id: 'author_aficionado',
    title: 'Author Aficionado',
    description: 'Explored the authors of From Serfs and Frauds.',
    icon: <UserIcon size={32} weight="duotone" />,
    category: 'Exploration',
  },
  {
    id: 'time_traveler',
    title: 'Time Traveler',
    description: 'Changelogs?',
    icon: <TimerIcon size={32} weight="duotone" />,
    category: 'Exploration',
  },
  {
    id: 'news_hound',
    title: 'News Hound',
    description: 'Checked out the latest news and updates.',
    icon: <CompassIcon size={32} weight="duotone" />,
    category: 'Exploration',
  },
  {
    id: 'log_diver',
    title: 'Log Diver',
    description: 'Explored the logs.',
    icon: <LogIcon size={32} weight="duotone" />,
    category: 'Exploration',
  },
  {
    id: 'project_pioneer',
    title: 'Project Pioneer',
    description: 'Discovered the projects page.',
    icon: <TerminalWindowIcon size={32} weight="duotone" />,
    category: 'Exploration',
  },
  {
    id: 'time_teller',
    title: 'Time Teller',
    description: 'I want to know the time.',
    icon: <TimerIcon size={32} weight="duotone" />,
    category: 'Tools',
  },
  {
    id: 'path_finder',
    title: 'Path Finder',
    description: 'Navigated to the Roadmap page.',
    icon: <KanbanIcon size={32} weight="duotone" />,
    category: 'Exploration',
  },
  {
    id: 'the_hacker',
    title: 'The Hacker',
    description: 'Opened the Command Palette.',
    icon: <TerminalWindowIcon size={32} weight="duotone" />,
    category: 'Tools',
  },
  {
    id: 'the_architect',
    title: 'The Architect',
    description: 'Enabled Blueprint or Hellenic mode.',
    icon: <ColumnsIcon size={32} weight="duotone" />,
    category: 'Visuals',
  },
  {
    id: 'retro_futurist',
    title: 'Retro Futurist',
    description: 'Enabled Vaporwave or Cyberpunk mode.',
    icon: <SunglassesIcon size={32} weight="duotone" />,
    category: 'Visuals',
  },
  {
    id: 'the_artist',
    title: 'The Artist',
    description: 'Enabled Sketchbook mode.',
    icon: <PaintBrushIcon size={32} weight="duotone" />,
    category: 'Visuals',
  },
  {
    id: 'retro_gamer',
    title: 'Retro Gamer',
    description: 'Enabled Game Boy mode.',
    icon: <GameControllerIcon size={32} weight="duotone" />,
    category: 'Visuals',
  },
  {
    id: 'glitch_hunter',
    title: 'Glitch Hunter',
    description: 'Discovered the Dystopian Glitch mode.',
    icon: <SkullIcon size={32} weight="duotone" />,
    category: 'Visuals',
  },
  {
    id: 'power_user',
    title: 'Power User',
    description: 'Visited the Settings page.',
    icon: <LightningIcon size={32} weight="duotone" />,
    category: 'Tools',
  },
  {
    id: 'novice_reader',
    title: 'Novice Reader',
    description: 'Read your first blog post.',
    icon: <BookOpenIcon size={32} weight="duotone" />,
    category: 'Content',
  },
  {
    id: 'avid_reader',
    title: 'Avid Reader',
    description: 'Read 5 different blog posts.',
    icon: <BookBookmarkIcon size={32} weight="duotone" />,
    category: 'Content',
  },
  {
    id: 'bookworm',
    title: 'Bookworm',
    description: 'Read 10 different blog posts. Impressive!',
    icon: <BooksIcon size={32} weight="duotone" />,
    category: 'Content',
  },
  {
    id: 'scholar',
    title: 'Scholar',
    description: 'Read 20 different blog posts. Impressive!',
    icon: <ChalkboardIcon size={32} weight="duotone" />,
    category: 'Content',
  },
  {
    id: 'milord',
    title: 'Mi Lord',
    description: 'Read 30 different blog posts. Mi Lord!',
    icon: <CastleTurretIcon size={32} weight="duotone" />,
    category: 'Content',
  },
  {
    id: 'hide_and_seek_master',
    title: 'Hide and Seek Master',
    description: 'Hid all roadmap status columns.',
    icon: <EyeSlashIcon size={32} weight="duotone" />,
    category: 'Exploration',
  },
  {
    id: 'the_medium',
    title: 'The Medium',
    description:
      'Successfully communicated with the code spirit and broke the infinite loop.',
    icon: <GhostIcon size={32} weight="duotone" />,
    category: 'Secret',
  },
  {
    id: 'leave_no_stone_unturned',
    title: 'Leave No Stone Unturned',
    description: 'Check application version.',
    icon: <MartiniIcon size={32} weight="duotone" />,
    category: 'Secret',
  },
  {
    id: 'her_daim',
    title: 'Her Daim...',
    description:'A hidden achievement',
    icon: <GhostIcon size={32} weight="duotone" />,
    category: 'Secret',
  },
];
