import {
  CompassIcon,
  TerminalWindowIcon,
  PaintBrushIcon,
  GameControllerIcon,
  ColumnsIcon,
  SunglassesIcon,
  UserIcon,
  LightningIcon,
  SkullIcon,
  BookOpenIcon,
  BookBookmarkIcon,
  BooksIcon,
  GhostIcon,
  EyeSlashIcon,
  ChalkboardIcon,
  CastleTurretIcon,
  MartiniIcon,
  TimerIcon,
  LogIcon,
  KanbanIcon,
  PhoneIcon,
  ShuffleIcon,
  QuestionMarkIcon,
  TrashIcon,
  MetronomeIcon,
  SpadeIcon,
  HeartIcon,
  DiamondIcon,
  EyeIcon,
  TargetIcon,
  BrainIcon,
  YinYangIcon,
  ArrowsClockwiseIcon,
  CirclesFourIcon,
} from '@phosphor-icons/react';

export const ACHIEVEMENTS = [
  {
    id: 'hello_world',
    title: 'Hello World',
    description: 'Welcome to Fezcodex.',
    icon: <CompassIcon size={32} weight="duotone" />,
    category: 'Exploration',
  },
  {
    id: 'curious_soul',
    title: 'Curious Soul',
    description: 'Visited the About Me page to learn who is behind this.',
    icon: <UserIcon size={32} weight="duotone" />,
    category: 'Exploration',
  },
  {
    id: 'author_aficionado',
    title: 'Author Aficionado',
    description: 'Explored the authors of From Serfs and Frauds.',
    icon: <UserIcon size={32} weight="duotone" />,
    category: 'Exploration',
  },
  {
    id: 'hide_and_seek_master',
    title: 'Hide and Seek Master',
    description: 'Hid all roadmap status columns.',
    icon: <EyeSlashIcon size={32} weight="duotone" />,
    category: 'Exploration',
  },
  {
    id: 'log_diver',
    title: 'Log Diver',
    description: 'Explored the logs.',
    icon: <LogIcon size={32} weight="duotone" />,
    category: 'Exploration',
  },
  {
    id: 'news_hound',
    title: 'News Hound',
    description: 'Checked out the latest news and updates.',
    icon: <CompassIcon size={32} weight="duotone" />,
    category: 'Exploration',
  },
  {
    id: 'path_finder',
    title: 'Path Finder',
    description: 'Navigated to the Roadmap page.',
    icon: <KanbanIcon size={32} weight="duotone" />,
    category: 'Exploration',
  },
  {
    id: 'project_pioneer',
    title: 'Project Pioneer',
    description: 'Discovered the projects page.',
    icon: <TerminalWindowIcon size={32} weight="duotone" />,
    category: 'Exploration',
  },
  {
    id: 'story_explorer',
    title: 'Story Explorer',
    description: 'Did you hear about the Serfs?',
    icon: <BookOpenIcon size={32} weight="duotone" />,
    category: 'Exploration',
  },
  {
    id: 'time_traveler',
    title: 'Time Traveler',
    description: 'Changelogs?',
    icon: <TimerIcon size={32} weight="duotone" />,
    category: 'Exploration',
  },
  {
    id: 'avid_reader',
    title: 'Avid Reader',
    description: 'Read 5 different blog posts.',
    icon: <BookBookmarkIcon size={32} weight="duotone" />,
    category: 'Content',
  },
  {
    id: 'bookworm',
    title: 'Bookworm',
    description: 'Read 10 different blog posts. Impressive!',
    icon: <BooksIcon size={32} weight="duotone" />,
    category: 'Content',
  },
  {
    id: 'milord',
    title: 'Mi Lord',
    description: 'Read 30 different blog posts. Mi Lord!',
    icon: <CastleTurretIcon size={32} weight="duotone" />,
    category: 'Content',
  },
  {
    id: 'novice_reader',
    title: 'Novice Reader',
    description: 'Read your first blog post.',
    icon: <BookOpenIcon size={32} weight="duotone" />,
    category: 'Content',
  },
  {
    id: 'scholar',
    title: 'Scholar',
    description: 'Read 20 different blog posts. Impressive!',
    icon: <ChalkboardIcon size={32} weight="duotone" />,
    category: 'Content',
  },
  {
    id: 'power_user',
    title: 'Power User',
    description: 'Visited the Settings page.',
    icon: <LightningIcon size={32} weight="duotone" />,
    category: 'Tools',
  },
  {
    id: 'the_hacker',
    title: 'The Hacker',
    description: 'Opened the Command Palette.',
    icon: <TerminalWindowIcon size={32} weight="duotone" />,
    category: 'Tools',
  },
  {
    id: 'time_teller',
    title: 'Time Teller',
    description: 'I want to know the time.',
    icon: <TimerIcon size={32} weight="duotone" />,
    category: 'Tools',
  },
  {
    id: 'glitch_hunter',
    title: 'Glitch Hunter',
    description: 'Discovered the Dystopian Glitch mode.',
    icon: <SkullIcon size={32} weight="duotone" />,
    category: 'Visuals',
  },
  {
    id: 'retro_futurist',
    title: 'Retro Futurist',
    description: 'Enabled Vaporwave or Cyberpunk mode.',
    icon: <SunglassesIcon size={32} weight="duotone" />,
    category: 'Visuals',
  },
  {
    id: 'retro_gamer',
    title: 'Retro Gamer',
    description: 'Enabled Game Boy mode.',
    icon: <GameControllerIcon size={32} weight="duotone" />,
    category: 'Visuals',
  },
  {
    id: 'the_architect',
    title: 'The Architect',
    description: 'Enabled Blueprint or Hellenic mode.',
    icon: <ColumnsIcon size={32} weight="duotone" />,
    category: 'Visuals',
  },
  {
    id: 'the_artist',
    title: 'The Artist',
    description: 'Enabled Sketchbook mode.',
    icon: <PaintBrushIcon size={32} weight="duotone" />,
    category: 'Visuals',
  },
  {
    id: 'and_heartbreak',
    title: '& Heartbreak',
    description: 'And my head keeps spinning.',
    icon: <ShuffleIcon size={32} weight="duotone" />,
    category: 'Secret',
  },
  {
    id: 'sos_signal',
    title: 'A Universal plea',
    description: 'THE universal plea.',
    icon: <PhoneIcon size={32} weight="duotone" />,
    category: 'Secret',
  },
  {
    id: 'all_eyez_on_me',
    title: 'All Eyez On Me',
    description: 'California knows how to party.',
    icon: <ShuffleIcon size={32} weight="duotone" />,
    category: 'Secret',
  },
  {
    id: 'barcode_man',
    title: 'Barcode Man',
    description: 'Beep beep on the back of the head',
    icon: <PhoneIcon size={32} weight="duotone" />,
    category: 'Secret',
  },
  {
    id: 'black',
    title: 'Black',
    description: 'Total darkness.',
    icon: <QuestionMarkIcon size={32} weight="duotone" />,
    category: 'Secret',
  },
  {
    id: 'boing',
    title: 'Boing...',
    description: 'Jumbo Jet.',
    icon: <QuestionMarkIcon size={32} weight="duotone" />,
    category: 'Secret',
  },
  {
    id: 'ctu_agent',
    title: 'CTU Agent',
    description: 'The clock is ticking...',
    icon: <PhoneIcon size={32} weight="duotone" />,
    category: 'Secret',
  },
  {
    id: 'call_me_generic',
    title: 'Call Me Generic',
    description: 'It is just 3 number repeating...',
    icon: <PhoneIcon size={32} weight="duotone" />,
    category: 'Secret',
  },
  {
    id: 'card_shark',
    title: 'Card Shark',
    description: 'Scored over 7 in Higher or Lower.',
    icon: <SpadeIcon size={32} weight="duotone" />,
    category: 'Secret',
  },
  {
    id: 'chaos_theory',
    title: 'Chaos Theory',
    description: 'The world shifts beneath your feet.',
    icon: <ArrowsClockwiseIcon size={32} weight="duotone" />,
    category: 'Secret',
  },
  {
    id: 'combo_breaker',
    title: 'Combo Breaker',
    description: 'Faster than a goldfish.',
    icon: <LightningIcon size={32} weight="duotone" />,
    category: 'Secret',
  },
  {
    id: 'critical_hit',
    title: 'Critical Hit',
    description: 'Nat...',
    icon: <QuestionMarkIcon size={32} weight="duotone" />,
    category: 'Secret',
  },
  {
    id: 'cyber_homie',
    title: 'Cyber Home',
    description: "There's no place like Cyber Home. Home Sweet Home",
    icon: <QuestionMarkIcon size={32} weight="duotone" />,
    category: 'Secret',
  },
  {
    id: 'daisy_daisy',
    title: 'Daisy, Daisy',
    description: "I'm afraid I can't do that",
    icon: <ShuffleIcon size={32} weight="duotone" />,
    category: 'Secret',
  },
  {
    id: 'dealing_with_a_kid',
    title: 'Dealing With a Kid',
    description: 'Oh, grow up...',
    icon: <PhoneIcon size={32} weight="duotone" />,
    category: 'Secret',
  },
  {
    id: 'devil',
    title: 'Devil',
    description: 'Did you try to summon more evil? What the hell...',
    icon: <PhoneIcon size={32} weight="duotone" />,
    category: 'Secret',
  },
  {
    id: 'dont_google',
    title: "Don't Google",
    description: "Don't Google It.",
    icon: <ShuffleIcon size={32} weight="duotone" />,
    category: 'Secret',
  },
  {
    id: 'dystopian_are_we',
    title: 'Dystopian, Are We',
    description: 'Is Big Brother still watching...',
    icon: <PhoneIcon size={32} weight="duotone" />,
    category: 'Secret',
  },
  {
    id: 'echo_in_the_void',
    title: 'Echo in the Void',
    description: 'Call out where no one listens.',
    icon: <GhostIcon size={32} weight="duotone" />,
    category: 'Secret',
  },
  {
    id: 'eidetic_memory',
    title: 'Eidetic Memory',
    description: 'Completed Memory Game in 18 moves or less.',
    icon: <TargetIcon size={32} weight="duotone" />,
    category: 'Secret',
  },
  {
    id: 'elite',
    title: 'Elite',
    description: 'elite...',
    icon: <ShuffleIcon size={32} weight="duotone" />,
    category: 'Secret',
  },
  {
    id: 'code_1337',
    title: 'Elite Error',
    description: 'Death came with a code.',
    icon: <TerminalWindowIcon size={32} weight="duotone" />,
    category: 'Secret',
  },
  {
    id: 'entropy_increaser',
    title: 'Entropy Increaser',
    description: 'Disorder is inevitable.',
    icon: <CirclesFourIcon size={32} weight="duotone" />,
    category: 'Secret',
  },
  {
    id: 'fast_eyes',
    title: 'Fast Eyes',
    description: 'Shut and open the eyes quickly.',
    icon: <ShuffleIcon size={32} weight="duotone" />,
    category: 'Secret',
  },
  {
    id: 'bsod',
    title: 'Fatal Error',
    description: '0x00000000',
    icon: <SkullIcon size={32} weight="duotone" />,
    category: 'Secret',
  },
  {
    id: 'feeling_lucky',
    title: 'Feeling Lucky',
    description: 'Surprise.',
    icon: <ShuffleIcon size={32} weight="duotone" />,
    category: 'Secret',
  },
  {
    id: 'feline',
    title: 'Feline',
    description: 'Feline on the line.',
    icon: <QuestionMarkIcon size={32} weight="duotone" />,
    category: 'Secret',
  },
  {
    id: 'galatasaray',
    title: 'Galatasaray',
    description: '1905',
    icon: <PhoneIcon size={32} weight="duotone" />,
    category: 'Secret',
  },
  {
    id: 'glitch_in_the_matrix',
    title: 'Glitch in the Matrix',
    description: 'Seek the paths that do not exist.',
    icon: <SkullIcon size={32} weight="duotone" />,
    category: 'Secret',
  },
  {
    id: 'her_daim',
    title: 'Her Daim...',
    description: 'A hidden achievement',
    icon: <GhostIcon size={32} weight="duotone" />,
    category: 'Secret',
  },
  {
    id: 'high_roller',
    title: 'High Roller',
    description: 'Scored over 14 in Higher or Lower.',
    icon: <HeartIcon size={32} weight="duotone" />,
    category: 'Secret',
  },
  {
    id: 'human_metronome',
    title: 'Human Metronome',
    description: 'Steady as a rock.',
    icon: <MetronomeIcon size={32} weight="duotone" />,
    category: 'Secret',
  },
  {
    id: 'immersive_sim_door_code',
    title: 'Immersive Sim Door Code',
    description: 'Looking Glass Studios loves Fahrenheit',
    icon: <PhoneIcon size={32} weight="duotone" />,
    category: 'Secret',
  },
  {
    id: 'indestructible',
    title: 'Indestructible',
    description: 'and it broke the floor...',
    icon: <ShuffleIcon size={32} weight="duotone" />,
    category: 'Secret',
  },
  {
    id: 'invaded_england',
    title: 'Invaded England',
    description: 'You just invaded England.',
    icon: <ShuffleIcon size={32} weight="duotone" />,
    category: 'Secret',
  },
  {
    id: 'ketchup',
    title: 'Ketchup',
    description: 'The Slow Pour. Good things come to those who wait.',
    icon: <ShuffleIcon size={32} weight="duotone" />,
    category: 'Secret',
  },
  {
    id: 'kobe',
    title: 'Kobe',
    description: 'Kobe...',
    icon: <PhoneIcon size={32} weight="duotone" />,
    category: 'Secret',
  },
  {
    id: 'konami_code',
    title: 'Konami Code',
    description: 'The classic sequence.',
    icon: <GameControllerIcon size={32} weight="duotone" />,
    category: 'Secret',
  },
  {
    id: 'leave_no_stone_unturned',
    title: 'Leave No Stone Unturned',
    description: 'Check application version.',
    icon: <MartiniIcon size={32} weight="duotone" />,
    category: 'Secret',
  },
  {
    id: 'legendary_gambler',
    title: 'Legendary Gambler',
    description: 'Scored over 20 in Higher or Lower.',
    icon: <DiamondIcon size={32} weight="duotone" />,
    category: 'Secret',
  },
  {
    id: 'm_for_murder',
    title: 'M for Murder',
    description: 'Murder on the line.',
    icon: <PhoneIcon size={32} weight="duotone" />,
    category: 'Secret',
  },
  {
    id: 'mind_palace',
    title: 'Mind Palace',
    description: 'Completed Memory Game in 14 moves or less.',
    icon: <BrainIcon size={32} weight="duotone" />,
    category: 'Secret',
  },
  {
    id: 'moms_spaghetti',
    title: "Mom's Spaghetti",
    description: 'Put your hands up for it.',
    icon: <ShuffleIcon size={32} weight="duotone" />,
    category: 'Secret',
  },
  {
    id: 'mr_halo_himself',
    title: 'Mr. Halo Himself',
    description: 'The SPARTAN is calling...',
    icon: <PhoneIcon size={32} weight="duotone" />,
    category: 'Secret',
  },
  {
    id: 'do_a_barrel_roll',
    title: 'My Head Spinning',
    description: 'You spin my head right round, right round.',
    icon: <ArrowsClockwiseIcon size={32} weight="duotone" />,
    category: 'Secret',
  },
  {
    id: 'new_dc_universe',
    title: 'New DC Universe',
    description: 'Let me reset the DC Universe',
    icon: <PhoneIcon size={32} weight="duotone" />,
    category: 'Secret',
  },
  {
    id: 'night_owl',
    title: 'Night Owl',
    description: 'The witching hour approaches.',
    icon: <EyeIcon size={32} weight="duotone" />,
    category: 'Secret',
  },
  {
    id: 'not_found',
    title: 'Not Found',
    description: 'Not Found',
    icon: <PhoneIcon size={32} weight="duotone" />,
    category: 'Secret',
  },
  {
    id: 'ocean',
    title: 'Ocean',
    description:
      'and George Clooney and Matt Damon and Julia Roberts and Brat Pitt and Andy Garcia and Bernie Mac...',
    icon: <QuestionMarkIcon size={32} weight="duotone" />,
    category: 'Secret',
  },
  {
    id: 'on_the_beat',
    title: 'On the Beat',
    description: 'Achieved exactly 90 BPM in the BPM Guesser.',
    icon: <MetronomeIcon size={32} weight="duotone" />,
    category: 'Secret',
  },
  {
    id: 'one_less_problem',
    title: 'One Less Problem',
    description: "but this rotary phone ain't one.",
    icon: <ShuffleIcon size={32} weight="duotone" />,
    category: 'Secret',
  },
  {
    id: 'open_24_hours',
    title: 'Open 24 Hours',
    description: "We're open 24 hours.",
    icon: <ShuffleIcon size={32} weight="duotone" />,
    category: 'Secret',
  },
  {
    id: 'operator',
    title: 'Operator',
    description: 'Looking for assistance?',
    icon: <PhoneIcon size={32} weight="duotone" />,
    category: 'Secret',
  },
  {
    id: 'perfect_timing',
    title: 'Perfect Timing',
    description: 'Stopped the stopwatch at exactly 10.00 seconds.',
    icon: <TimerIcon size={32} weight="duotone" />,
    category: 'Secret',
  },
  {
    id: 'pie',
    title: 'Pie',
    description: '3 is just enough.',
    icon: <PhoneIcon size={32} weight="duotone" />,
    category: 'Secret',
  },
  {
    id: 'rip_and_tear',
    title: 'Rip and Tear',
    description: 'Until it is done.',
    icon: <QuestionMarkIcon size={32} weight="duotone" />,
    category: 'Secret',
  },
  {
    id: 'cheater',
    title: 'Rule Breaker',
    description: 'Admitting it is the first step.',
    icon: <SkullIcon size={32} weight="duotone" />,
    category: 'Secret',
  },
  {
    id: 'savage',
    title: 'Savage',
    description: 'Because we ran out of soda...',
    icon: <QuestionMarkIcon size={32} weight="duotone" />,
    category: 'Secret',
  },
  {
    id: 'sharp_eye',
    title: 'Sharp Eye',
    description: 'Completed Memory Game in 24 moves or less.',
    icon: <EyeIcon size={32} weight="duotone" />,
    category: 'Secret',
  },
  {
    id: 'skyrim',
    title: 'Skyrim',
    description: 'Cannot get a better day to release the most released game',
    icon: <PhoneIcon size={32} weight="duotone" />,
    category: 'Secret',
  },
  {
    id: 'some_bodies_gonna_get_it',
    title: 'Some Bodies Gonna Get It',
    description: 'Mark Henry enters the ring...',
    icon: <ShuffleIcon size={32} weight="duotone" />,
    category: 'Secret',
  },
  {
    id: 'speaking_clock',
    title: 'Speaking Clock',
    description: 'A Speaking Clock that does not really tell time.',
    icon: <PhoneIcon size={32} weight="duotone" />,
    category: 'Secret',
  },
  {
    id: 'system',
    title: 'System',
    description:
      "Delete It. To make your computer run faster. (Don't actually do this).",
    icon: <QuestionMarkIcon size={32} weight="duotone" />,
    category: 'Secret',
  },
  {
    id: 'teapot',
    title: 'Teapot',
    description: 'because it is a teapot.',
    icon: <QuestionMarkIcon size={32} weight="duotone" />,
    category: 'Secret',
  },
  {
    id: 'the_answer',
    title: 'The Answer',
    description:
      'The Answer to the Ultimate Question of Life, the Universe, and Everything',
    icon: <PhoneIcon size={32} weight="duotone" />,
    category: 'Secret',
  },
  {
    id: 'the_cartographer',
    title: 'The Cartographer',
    description: 'Map the territory.',
    icon: <CompassIcon size={32} weight="duotone" />,
    category: 'Secret',
  },
  {
    id: 'the_emergency',
    title: 'The Emergency',
    description: 'Is everything okay?',
    icon: <PhoneIcon size={32} weight="duotone" />,
    category: 'Secret',
  },
  {
    id: 'the_holo_grammy',
    title: 'The Holo-Grammy',
    description: 'I’ll be right by your side.',
    icon: <ShuffleIcon size={32} weight="duotone" />,
    category: 'Secret',
  },
  {
    id: 'the_last_good_gen',
    title: 'The Last Good Generation',
    description: 'Playstation won after this...',
    icon: <QuestionMarkIcon size={32} weight="duotone" />,
    category: 'Secret',
  },
  {
    id: 'the_medium',
    title: 'The Medium',
    description:
      'Successfully communicated with the code spirit and broke the infinite loop.',
    icon: <GhostIcon size={32} weight="duotone" />,
    category: 'Secret',
  },
  {
    id: 'the_monitor',
    title: 'The Monitor',
    description: 'You are the reclaimer.',
    icon: <ShuffleIcon size={32} weight="duotone" />,
    category: 'Secret',
  },
  {
    id: 'the_number_of_monkeys',
    title: 'The Number of Monkeys',
    description: 'Ask Bruce.',
    icon: <ShuffleIcon size={32} weight="duotone" />,
    category: 'Secret',
  },
  {
    id: 'the_order',
    title: 'The Order',
    description: 'It will be done, my lord',
    icon: <ShuffleIcon size={32} weight="duotone" />,
    category: 'Secret',
  },
  {
    id: 'the_paradox',
    title: 'The Paradox',
    description: 'Look for the tool within the tool.',
    icon: <QuestionMarkIcon size={32} weight="duotone" />,
    category: 'Secret',
  },
  {
    id: 'the_real_retro_gamer',
    title: 'The Real Retro Gamer',
    description: 'One button, one joystick, infinite fun.',
    icon: <QuestionMarkIcon size={32} weight="duotone" />,
    category: 'Secret',
  },
  {
    id: 'truth_is_out_there',
    title: 'The Truth Is Out There',
    description: "You're Naruto-running straight into the base.",
    icon: <ShuffleIcon size={32} weight="duotone" />,
    category: 'Secret',
  },
  {
    id: 'the_void_stares_back',
    title: 'The Void Stares Back',
    description: 'Stare into the abyss...',
    icon: <EyeIcon size={32} weight="duotone" />,
    category: 'Secret',
  },
  {
    id: 'the_worst_agent',
    title: 'The Worst Agent',
    description: 'If 1.5 is the answer, What is the question?',
    icon: <PhoneIcon size={32} weight="duotone" />,
    category: 'Secret',
  },
  {
    id: 'time_traveller_system',
    title: 'Time Traveller',
    description: 'Go back to where it all began.',
    icon: <TimerIcon size={32} weight="duotone" />,
    category: 'Secret',
  },
  {
    id: 'trinity_calling',
    title: 'Trinity Calling',
    description: 'A Matrix reference, in this day and age...',
    icon: <PhoneIcon size={32} weight="duotone" />,
    category: 'Secret',
  },
  {
    id: 'van_halen',
    title: 'Van Halen',
    description: 'Rock on.',
    icon: <QuestionMarkIcon size={32} weight="duotone" />,
    category: 'Secret',
  },
  {
    id: 'wireless',
    title: 'Wireless',
    description: 'Trying to connect a rotary phone to the router? Good luck.',
    icon: <QuestionMarkIcon size={32} weight="duotone" />,
    category: 'Secret',
  },
  {
    id: 'www',
    title: 'World Wide Web',
    description: 'Unencrypted browsing? Living on the edge',
    icon: <QuestionMarkIcon size={32} weight="duotone" />,
    category: 'Secret',
  },
  {
    id: 'you_smart',
    title: 'You are not Stupid',
    description: 'and You Know Math',
    icon: <QuestionMarkIcon size={32} weight="duotone" />,
    category: 'Secret',
  },
  {
    id: 'zen',
    title: 'Zen',
    description: 'Turned it into a proper garden.',
    icon: <YinYangIcon size={32} weight="duotone" />,
    category: 'Secret',
  },
  {
    id: 'east_side',
    title: 'East Side',
    description: 'Opened the Right Side.',
    icon: <ColumnsIcon size={32} weight="duotone" />,
    category: 'Secret',
  },
  {
    id: 'su-done',
    title: 'Privilege Escalation',
    description: 'Escalate your privileges in a new environment',
    icon: <TerminalWindowIcon size={32} weight="duotone" />,
    category: 'Secret',
  },
  {
    id: 'clean_slate',
    title: 'Clean Slate',
    description: 'Tabula Rasa.',
    icon: <TrashIcon size={32} weight="duotone" />,
    category: 'Secret',
  },
  {
    id: 'access_granted',
    title: 'Access Granted',
    description: 'Decrypted the hidden terminal sequence.',
    icon: <TerminalWindowIcon size={32} weight="duotone" />,
    category: 'Secret',
  },
];
