import React, { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { useVisualSettings } from '../context/VisualSettingsContext';

const splashTexts = [
  'Any fool can write code that a computer can understand. Good programmers write code that humans can understand. ~ Martin Fowler',
  'First, solve the problem. Then, write the code. ~ John Johnson',
  'Experience is the name everyone gives to their mistakes. ~ Oscar Wilde',
  'In order to be irreplaceable, one must always be different. ~ Coco Chanel',
  'Java is to JavaScript what car is to Carpet. ~ Chris Heilmann',
  'Knowledge is power. ~ Francis Bacon',
  'Simplicity is the soul of efficiency. ~ Austin Freeman',
  'Code is like humor. When you have to explain it, it’s bad. ~ Cory House',
  'Fix the cause, not the symptom. ~ Steve Maguire',
  'Optimism is an occupational hazard of programming. ~ Kent Beck',
  'Make it work, make it right, make it fast. ~ Kent Beck',
  'Deleted code is debugged code. ~ Jeff Sickel',
  'It’s not a bug – it’s an undocumented feature. ~ Anonymous',
  'Software is a great combination between artistry and engineering. ~ Bill Gates',
  'The best way to predict the future is to invent it. ~ Alan Kay',
  'Talk is cheap. Show me the code. ~ Linus Torvalds',
  'Programs must be written for people to read, and only incidentally for machines to execute. ~ Harold Abelson',
  'Truth can only be found in one place: the code. ~ Robert C. Martin',
  'Walking on water and developing software from a specification are easy if both are frozen. ~ Edward V. Berard',
  "A language that doesn't affect the way you think about programming, is not worth knowing. ~ Alan Perlis",
  'The most disastrous thing that you can ever learn is your first programming language. ~ Alan Kay',
  'Computer science education cannot make anybody an expert programmer any more than studying brushes and pigment can make somebody an expert painter. ~ Eric S. Raymond',
  'Measuring programming progress by lines of code is like measuring aircraft building progress by weight. ~ Bill Gates',
  'There are only two kinds of languages: the ones people complain about and the ones nobody uses. ~ Bjarne Stroustrup',
  'Fezcodex: Now with 50% more pixels! ~ Fezcodex',
  "Don't dig straight down! ~ Minecraft",
  'Creeper? Aww man... ~ Minecraft',
  'Also try Terraria! ~ Minecraft',
  'Follow the white rabbit. ~ The Matrix',
  'The cake is a lie. ~ Portal',
  'All your base are belong to us. ~ Zero Wing',
  "It's dangerous to go alone! Take this. ~ The Legend of Zelda",
  'Do a barrel roll! ~ Star Fox 64',
  'Snake? Snake? SNAKEEEE! ~ Metal Gear Solid',
  'War. War never changes. ~ Fallout',
  'Stay awhile and listen. ~ Diablo II',
  'I used to be an adventurer like you, then I took an arrow in the knee. ~ Skyrim',
  'Praise the sun! ~ Dark Souls',
  'You died. ~ Dark Souls',
  'Hey! Listen! ~ Ocarina of Time',
  'Objection! ~ Phoenix Wright',
  'Finish him! ~ Mortal Kombat',
  "Gotta catch 'em all! ~ Pokémon",
  'A winner is you! ~ Pro Wrestling',
  'Thank you Mario! But our princess is in another castle! ~ Super Mario Bros.',
  'What is a man? A miserable little pile of secrets! ~ Castlevania: SOTN',
  'Wake up, Mr. Freeman. Wake up and smell the ashes. ~ Half-Life 2',
  'Protocol 3: Protect the Pilot. ~ Titanfall 2',
  'Would you kindly? ~ BioShock',
  'Did I ever tell you the definition of insanity? ~ Far Cry 3',
  "Nothing is true, everything is permitted. ~ Assassin's Creed",
  "Requiescat in pace. ~ Assassin's Creed",
  'Endure and survive. ~ The Last of Us',
  'Keep calm and carry on. ~ Wartime Poster',
  'May the Force be with you. ~ Star Wars',
  'Live long and prosper. ~ Star Trek',
  'Winter is coming. ~ Game of Thrones',
  'To infinity and beyond! ~ Toy Story',
  "I'll be back. ~ The Terminator",
  'Houston, we have a problem. ~ Apollo 13',
  'Elementary, my dear Watson. ~ Sherlock Holmes',
  "Frankly, my dear, I don't give a damn. ~ Gone with the Wind",
  "Here's looking at you, kid. ~ Casablanca",
  "You can't handle the truth! ~ A Few Good Men",
  'I see dead people. ~ The Sixth Sense',
  'Why so serious? ~ The Dark Knight',
  'Just keep swimming. ~ Finding Nemo',
  'Adventure is out there! ~ Up',
  "Life moves pretty fast. If you don't stop and look around once in a while, you could miss it. ~ Ferris Bueller's Day Off",
  'Great Scott! ~ Back to the Future',
  'I am your father. ~ Star Wars',
  'My precious. ~ Lord of the Rings',
  'You shall not pass! ~ Lord of the Rings',
  'One does not simply walk into Mordor. ~ Lord of the Rings',
  'For Frodo. ~ Lord of the Rings',
  'Of course it is happening inside your head, Harry, but why on earth should that mean that it is not real? ~ Harry Potter',
  'Yer a wizard, Harry. ~ Harry Potter',
  'I solemnly swear that I am up to no good. ~ Harry Potter',
  'Mischief managed. ~ Harry Potter',
  'After all this time? Always. ~ Harry Potter',
  'Do not pity the dead, Harry. Pity the living, and, above all, those who live without love. ~ Harry Potter',
  'Happiness can be found, even in the darkest of times, if one only remembers to turn on the light. ~ Harry Potter',
  'It does not do to dwell on dreams and forget to live. ~ Harry Potter',
  'The things we lose have a way of coming back to us in the end, if not always in the way we expect. ~ Harry Potter',
  "We've all got both light and dark inside us. What matters is the part we choose to act on. That's who we really are. ~ Harry Potter",
  'Words are, in my not-so-humble opinion, our most inexhaustible source of magic. ~ Harry Potter',
  "Wit beyond measure is man's greatest treasure. ~ Harry Potter",
  'I am Iron Man. ~ Avengers: Endgame',
  'Avengers, assemble! ~ Avengers: Endgame',
  'I can do this all day. ~ Captain America',
  'On your left. ~ Captain America: The Winter Soldier',
  'We are Groot. ~ Guardians of the Galaxy',
  'Wakanda Forever! ~ Black Panther',
  'I am inevitable. ~ Avengers: Endgame',
  'And I... am... Iron Man. ~ Avengers: Endgame',
  'Whatever it takes. ~ Avengers: Endgame',
  'I love you 3000. ~ Avengers: Endgame',
  "That's my secret, Captain. I'm always angry. ~ The Avengers",
  "Dormammu, I've come to bargain. ~ Doctor Strange",
  'Dance off, bro! ~ Guardians of the Galaxy',
  'Get help! Please! My brother is dying! ~ Thor: Ragnarok',
  "He's a friend from work! ~ Thor: Ragnarok",
  'Puny god. ~ The Avengers',
  'Genius, billionaire, playboy, philanthropist. ~ The Avengers',
  'I have nothing to prove to you. ~ Captain Marvel',
  'Higher, further, faster. ~ Captain Marvel',
  "I can't control their fear, only my own. ~ Captain America: Civil War",
  'You took everything from me! ~ Avengers: Endgame',
  "I don't even know who you are. ~ Avengers: Endgame",
  'Reality is often disappointing. ~ Avengers: Infinity War',
  'Perfectly balanced, as all things should be. ~ Avengers: Infinity War',
  'The hardest choices require the strongest wills. ~ Avengers: Infinity War',
  "Fun isn't something one considers when balancing the universe. ~ Avengers: Infinity War",
  'This does put a smile on my face. ~ Avengers: Infinity War',
  'You should have gone for the head. ~ Avengers: Infinity War',
  'I am mighty! ~ Thor',
  'Beware the rubber ducky. ~ Programmer Humor',
  'Sudo apt-get install life. ~ Linux Humor',
  'Keep your friends close, and your cursors closer. ~ Programmer Humor',
  'Save early, save often. ~ Gamer Wisdom',
  "Don't feed the trolls. ~ Internet Rule",
  'RTFM: Read The Friendly Manual. ~ Tech Support',
  'PEBKAC: Problem Exists Between Keyboard And Chair. ~ Tech Support',
  'ID10T Error. ~ Tech Support',
  'Layer 8 Issue. ~ Networking Humor',
  'Have you tried forcing an unexpected reboot? ~ The IT Crowd',
  'Turning coffee into code since 1990. ~ Programmer Life',
  'There is no place like 127.0.0.1 ~ Network Humor',
  'Home is where the wifi connects automatically. ~ Modern Proverb',
  "I'm not lazy, I'm just on energy saving mode. ~ Humor",
  '404: Motivation not found. ~ Web Humor',
  'Ctrl+C, Ctrl+V is my superpower. ~ Developer Truth',
  'I write code, therefore I am. ~ Descartes 2.0',
  'To err is human, to debug divine. ~ Developer Wisdom',
  'Real programmers count from 0. ~ Coding Fact',
  'A computer once beat me at chess, but it was no match for me at kick boxing. ~ Emo Philips',
  'Artificial Intelligence is no match for Natural Stupidity. ~ Unknown',
  "I don't need a life, I have a computer. ~ Geek Life",
  'My software never has bugs. It just develops random features. ~ Developer Humor',
  'Code never lies, comments sometimes do. ~ Coding Truth',
  'Documentation is like sex: when it is good, it is very, very good; and when it is bad, it is better than nothing. ~ Dick Brandon',
  "One man's crappy software is another man's full time job. ~ Jessica Gaston",
  'Programming is 10% science, 20% ingenuity, and 70% getting the ingenuity to work with the science. ~ Unknown',
  "If at first you don't succeed; call it version 1.0 ~ Unknown",
  'The definition of a legacy system: one that works. ~ Unknown',
  'Perfection is achieved not when there is nothing more to add, but rather when there is nothing more to take away. ~ Antoine de Saint-Exupéry',
  'Simplicity is the ultimate sophistication. ~ Leonardo da Vinci',
  'Impossible is nothing. ~ Adidas',
  'History is written by the victors. ~ Captain Price',
  'Five years ago, I lost 30,000 men in the blink of an eye. ~ General Shepherd',
  "The healthy human mind doesn't wake up in the morning thinking this is its last day on Earth. ~ Captain Price",
  "The world's on fire. Let's go to work. ~ Sandman",
  'No Russian. ~ Makarov',
  "What kind of name is 'Soap', anyway? ~ Captain Price",
  'I used to be an adventurer like you, then I took an arrow in the knee. ~ Guard',
  'Fus Ro Dah! ~ Dragonborn',
  'Stop right there, criminal scum! ~ Imperial Guard',
  'Let me guess... someone stole your sweetroll? ~ Guard',
  "I've fought mudcrabs more fearsome than you! ~ NPC",
  "Hey you, you're finally awake. ~ Ralof",
  'Patrolling the Mojave almost makes you wish for a nuclear winter. ~ NCR Trooper',
  'War. War never changes. ~ Narrator (Fallout)',
  'Degenerates like you belong on a cross. ~ Legionary',
  'The Truth is, the game was rigged from the start. ~ Benny',
  'I survived because the fire inside burned brighter than the fire around me. ~ Joshua Graham',
  "Maybe Khans kill people without looking them in the face, but I ain't a fink, dig? ~ Benny",
  'Tunnel Snakes Rule! ~ Tunnel Snakes',
  'A man chooses, a slave obeys. ~ Andrew Ryan',
  'Look at you, hacker: a pathetic creature of meat and bone. ~ SHODAN',
  'The right man in the wrong place can make all the difference in the world. ~ G-Man',
  "It's time to kick ass and chew bubble gum... and I'm all out of gum. ~ Duke Nukem",
  'Nothing is true, everything is permitted. ~ Ezio Auditore',
  'Requiescat in pace. ~ Ezio Auditore',
  'Seven-six-two millimeter. Full metal jacket. ~ Full Metal Jacket',
  "Good men mean well. We just don't always end up doing well. ~ Isaac Clarke",
  'Endure and survive. ~ Ellie',
  "I'm a survivor, Black Lung! ~ Micah Bell",
  'You, sir, are a fish. ~ Arthur Morgan',
  'I have a plan! ~ Dutch van der Linde',
  'LENNYYYYY! ~ Arthur Morgan',
  'Just one more score, Arthur! ~ Dutch van der Linde',
  'Faith, Arthur, faith! ~ Dutch van der Linde',
  'Outlaws for life. ~ Red Dead Redemption 2',
  'Stand in the ashes of a trillion dead souls, and ask the ghosts if honor matters. ~ Javik',
  'I am the very model of a scientist salarian. ~ Mordin Solus',
  "Keelah se'lai. ~ Tali'Zorah",
  'Had to be me. Someone else might have gotten it wrong. ~ Mordin Solus',
  'Does this unit have a soul? ~ Legion',
  "I'm Commander Shepard, and this is my favorite store on the Citadel. ~ Commander Shepard",
  'I should go. ~ Commander Shepard',
  "It's a me, Mario! ~ Mario",
  'Thank you Mario! But our princess is in another castle! ~ Toad',
  'Do a barrel roll! ~ Peppy Hare',
  'All your base are belong to us. ~ Zero Wing',
  'The cake is a lie. ~ Portal',
  'Are you still there? ~ Turret',
  "Cave Johnson, we're done here. ~ Cave Johnson",
  'Combustible lemons! ~ Cave Johnson',
  'Space? SPACE! ~ Space Core',
  "I'm a potato. ~ GLaDOS",
  'Wheatley? More like Moron! ~ GLaDOS',
  "Science isn't about WHY. It's about WHY NOT. ~ Cave Johnson",
  'Aperture Science: We do what we must because we can. ~ GLaDOS',
  'Prepare for unforeseen consequences. ~ G-Man',
  'Wake up and smell the ashes. ~ G-Man',
  'Rise and shine, Mr. Freeman. ~ G-Man',
  "Don't make a girl a promise if you know you can't keep it. ~ Cortana",
  'Finish the fight. ~ Master Chief',
  'I need a weapon. ~ Master Chief',
  'Our numbers will darken the sky of every world. ~ Harbinger',
  'You exist because we allow it, and you will end because we demand it. ~ Sovereign',
  'Sir, finishing this fight. ~ Master Chief',
  'Wake me when you need me. ~ Master Chief',
  'The sun is a wondrous body. Like a magnificent father! ~ Solaire',
  'Praise the sun! o/ ~ Solaire',
  'Git gud. ~ Dark Souls Community',
  'You died. ~ Dark Souls',
  'Bondfire Lit. ~ Dark Souls',
  'Bear- seek- seek- lest- ~ Emerald Herald',
  'Fear the Old Blood. ~ Master Willem',
  'A hunter must hunt. ~ Eileen the Crow',
  'Tonight, Gehrman joins the hunt. ~ Gehrman',
  'Grant us eyes! ~ Micolash',
  'Oooooh, majestic! A hunter is a hunter, even in a dream. ~ Micolash',
  'Hesitation is defeat. ~ Isshin, the Sword Saint',
  'MY NAME IS GYOUBU MASATAKA ONIWA! ~ Gyoubu Oniwa',
  'Snake? Snake? SNAKEEEE! ~ Colonel Campbell',
  "A Hind D? What's a Russian gunship doing here? ~ Snake",
  "You're pretty good. ~ Revolver Ocelot",
  'La-li-lu-le-lo. ~ The Patriots',
  'Kept you waiting, huh? ~ Snake',
  'Nanomachines, son! ~ Senator Armstrong',
  "I'm nuclear! I'm wild! ~ Metal Gear Solid V",
  'Rules of Nature! ~ Metal Gear Rising',
  'Sins of the Father. ~ Metal Gear Solid V',
  'The world needs only one Big Boss. ~ Major Zero',
  'Solid Snake is the best! ~ Otacon',
  'Liquid!!!! ~ Snake',
  'Metal Gear?! ~ Snake',
  'Why are we still here? Just to suffer? ~ Miller',
  "Kaz, I'm already a demon. ~ Big Boss",
  "You're breathtaking! ~ Keanu Reeves",
  'Wake up, Samurai! We have a city to burn. ~ Johnny Silverhand',
  'I used to be a programmer like you, then I took an error in the logic. ~ Developer Humor',
  'Fezcodex: The digital frontier. ~ Fezcodex',
  'Stay brutal, my friends. ~ Fezcodex',
  'Code hard, dream harder. ~ Fezcodex',
  'The grid. A digital frontier. I tried to picture clusters of information as they moved through the computer. ~ Tron: Legacy',
  'What if I told you that everything you knew was a lie? ~ The Matrix',
  'Welcome to the desert of the real. ~ The Matrix',
  'Free your mind. ~ The Matrix',
  'I know kung fu. ~ The Matrix',
  'Show me. ~ The Matrix',
  'There is no spoon. ~ The Matrix',
  "He's beginning to believe. ~ The Matrix",
  'Dodge this. ~ The Matrix',
  'Mr. Anderson! ~ The Matrix',
  'Not like this. Not like this. ~ The Matrix',
  'Choice is an illusion, created between those with power, and those without. ~ The Matrix Reloaded',
  'Everything that has a beginning has an end. ~ The Matrix Revolutions',
  "I'm in. ~ Hacker Movie Trope",
  'Hack the planet! ~ Hackers',
  'Zero Cool? Cereal Killer? ~ Hackers',
  'Mess with the best, die like the rest. ~ Hackers',
  'Pool on the roof must have a leak. ~ Hackers',
  'Hackers of the world, unite! ~ Hackers',
  "Type 'help' for a list of commands. ~ CLI",
  'Searching for hidden treasures... ~ RPG',
  'Deciphering ancient scripts... ~ Adventure',
  'Unlocking new secrets... ~ Game',
  'The vault is open. ~ Borderlands',
  'Welcome back, Commander. ~ XCOM',
  'Mission starts in T-minus 10 seconds. ~ FPS',
  'Good luck, have fun! ~ Gamer Etiquette',
  'GG WP. ~ Gamer Etiquette',
  'GL HF. ~ Gamer Etiquette',
  'The grind never stops. ~ MMO',
  'Just one more turn... ~ Civilization',
  'One more game! ~ Every Gamer',
  'Victory! ~ Victory Screen',
  'Defeat. ~ Game Over',
  'Draw. ~ Game Over',
  'Play of the Game! ~ Overwatch',
  'End of the line. ~ Generic Villain',
  'The Other Side. ~ Unknown',
  'War. War never changes. ~ Fallout',
  'I used to be an adventurer like you, then I took an arrow in the knee. ~ Skyrim',
  'Remember, no Russian. ~ Call of Duty: MW2',
  'Press F to pay respects. ~ Call of Duty: AW',
  'Bravo Six, going dark. ~ Call of Duty: MW',
  'The numbers Mason, what do they mean?! ~ Call of Duty: Black Ops',
  "Hey, you. You're finally awake. ~ Skyrim",
  'Let me guess... someone stole your sweetroll. ~ Skyrim',
  'Do a barrel roll! ~ Star Fox 64',
  "It's dangerous to go alone! Take this. ~ The Legend of Zelda",
  'The cake is a lie. ~ Portal',
  'A man chooses, a slave obeys. ~ BioShock',
  'Would you kindly? ~ BioShock',
  'Protocol 3: Protect the Pilot. ~ Titanfall 2',
  'Standby for Titanfall. ~ Titanfall',
  'Wake up, Mr. Freeman. Wake up and smell the ashes. ~ Half-Life 2',
  'The right man in the wrong place can make all the difference in the world. ~ Half-Life 2',
  'Endure and survive. ~ The Last of Us',
  'Kept you waiting, huh? ~ Metal Gear Solid',
  'Snake? Snake? SNAKEEEE! ~ Metal Gear Solid',
  'Praise the sun! ~ Dark Souls',
  'You died. ~ Dark Souls',
  'Finish him! ~ Mortal Kombat',
  'Get over here! ~ Mortal Kombat',
  'All your base are belong to us. ~ Zero Wing',
  'Stay awhile and listen. ~ Diablo II',
  'Stop right there, criminal scum! ~ Oblivion',
  'Khajiit has wares, if you have coin. ~ Skyrim',
  'FUS RO DAH! ~ Skyrim',
  "It's a me, Mario! ~ Super Mario 64",
  'Thank you Mario! But our princess is in another castle! ~ Super Mario Bros.',
  "Gotta catch 'em all! ~ Pokémon",
  'Prepare for unforeseen consequences. ~ Half-Life 2',
  "Requiescat in pace. ~ Assassin's Creed",
  "Nothing is true, everything is permitted. ~ Assassin's Creed",
  'Did I ever tell you the definition of insanity? ~ Far Cry 3',
  'Finish the fight. ~ Halo 3',
  'I need a weapon. ~ Halo 2',
  'Sir, finishing this fight. ~ Halo 2',
  'Wake me when you need me. ~ Halo 3',
  'Wort wort wort! ~ Halo',
  'Rip and tear, until it is done. ~ DOOM',
  'Against all the evil that Hell can conjure, all the wickedness that mankind can produce, we will send unto them... only you. ~ DOOM',
  'Stay frosty. ~ Call of Duty: MW',
  "Mission failed, we'll get 'em next time. ~ Call of Duty: MW2",
  "50,000 people used to live here. Now it's a ghost town. ~ Call of Duty: MW",
  'Ramirez! Do everything! ~ Call of Duty: MW2',
  'Assuming direct control. ~ Mass Effect 2',
  "I'm Commander Shepard, and this is my favorite store on the Citadel. ~ Mass Effect 2",
  'Had to be me. Someone else might have gotten it wrong. ~ Mass Effect 3',
  'Does this unit have a soul? ~ Mass Effect 3',
  'Eyes up, Guardian. ~ Destiny',
  "Whether we wanted it or not, we've stepped into a war with the Cabal on Mars. ~ Destiny",
  'Welcome to the League of Draven. ~ League of Legends',
  'Jobs done. ~ Warcraft III',
  'Frostmourne hungers. ~ Warcraft III',
  'For the Horde! ~ World of Warcraft',
  'For the Alliance! ~ World of Warcraft',
  'You are not prepared! ~ World of Warcraft',
  'My life for Aiur! ~ StarCraft',
  'Spawn more Overlords. ~ StarCraft',
  'Construction complete. ~ Command & Conquer',
  'Kirov reporting. ~ Command & Conquer: Red Alert 2',
  'Nuclear launch detected. ~ StarCraft',
  'Carrier has arrived. ~ StarCraft',
  'Wololo! ~ Age of Empires',
  'Stay in the shadows. ~ Thief',
  'Glory to Arstotzka. ~ Papers, Please',
  'Papers, please. ~ Papers, Please',
  'Objection! ~ Phoenix Wright',
  'Hold it! ~ Phoenix Wright',
  'Take that! ~ Phoenix Wright',
  'Cornered! ~ Phoenix Wright',
  'Hey! Listen! ~ Ocarina of Time',
  'Snaaaake! ~ Metal Gear Solid',
  'Metal Gear?! ~ Metal Gear Solid',
  'La-li-lu-le-lo. ~ Metal Gear Solid',
  'Nanomachines, son. ~ Metal Gear Rising',
  'Rules of Nature! ~ Metal Gear Rising',
  'Memes. The DNA of the soul. ~ Metal Gear Rising',
  'Tonight, Gehrman joins the hunt. ~ Bloodborne',
  'Fear the old blood. ~ Bloodborne',
  'Ah, Kos, or some say Kosm... ~ Bloodborne',
  'Hesitation is defeat. ~ Sekiro',
  'Sekiro! ~ Sekiro',
  'Boy! ~ God of War',
  "Don't be sorry, be better. ~ God of War",
  'Close your heart to it. ~ God of War',
  "Wind's howling. ~ The Witcher 3",
  "Damn you're ugly. ~ The Witcher 3",
  'How about a round of Gwent? ~ The Witcher 3',
  'Pam pa ram, pam pam pa ram. ~ The Witcher 3',
  'Praise Geraldo. ~ The Witcher 3 Community',
  'Protocol 1: Link to Pilot. ~ Titanfall 2',
  'Protocol 2: Uphold the Mission. ~ Titanfall 2',
  'Trust me. ~ Titanfall 2',
  "Voodoo 1, Viper's on station. Your journey ends here, Pilot. The skies belong to me. Nowhere to run, nowhere to hide. ~ Titanfall 2",
  'Pipe pipe pipe pipe pipe. ~ Titanfall 2',
  'Slow down! ~ Unknown',
  'Looking good! ~ Rick and Morty',
  'My man! ~ Rick and Morty',
  'Yes! ~ Rick and Morty',
  'Baker Street. ~ Sherlock Holmes',
  'Element zero. ~ Mass Effect',
  'Mass Effect fields. ~ Mass Effect',
  'Biotics. ~ Mass Effect',
  'Tech armor. ~ Mass Effect',
  'Omni-tool. ~ Mass Effect',
  'Medi-gel. ~ Mass Effect',
  'Thermal clips. ~ Mass Effect',
  'Eezo. ~ Mass Effect',
  'Paragon. ~ Mass Effect',
  'Renegade. ~ Mass Effect',
  'Spectre. ~ Mass Effect',
  'N7. ~ Mass Effect',
  'Normandy. ~ Mass Effect',
  'Mako. ~ Mass Effect',
  'Hammerhead. ~ Mass Effect',
  'Citadel. ~ Mass Effect',
  'Omega. ~ Mass Effect',
  'Illium. ~ Mass Effect',
  'Tuchanka. ~ Mass Effect',
  'Palaven. ~ Mass Effect',
  'Thessia. ~ Mass Effect',
  "Sur'Kesh. ~ Mass Effect",
  'Rachni. ~ Mass Effect',
  'Will you comply? ~ Fallout 4',
];

const SplashText = ({ className }) => {
  const [splashText, setSplashText] = useState('');
  const { isSplashTextEnabled } = useVisualSettings();

  useEffect(() => {
    // Select a random splash text on mount
    const randomText =
      splashTexts[Math.floor(Math.random() * splashTexts.length)];
    setSplashText(randomText);
  }, []);

  if (!splashText || !isSplashTextEnabled) return null;

  return (
    <AnimatePresence>
      <motion.span
        initial={{ scale: 0, opacity: 0 }}
        animate={{
          scale: [1, 1.1, 1],
          opacity: 1,
          rotate: -20,
        }}
        transition={{
          scale: {
            duration: 0.5,
            repeat: Infinity,
            repeatType: 'reverse',
          },
          opacity: { duration: 0.5 },
          rotate: { duration: 0 },
        }}
        className={`absolute -top-4 -right-4 md:-top-6 md:-right-6 text-yellow-300 text-xs md:text-sm font-bold tracking-normal z-50 whitespace-nowrap pointer-events-none select-none drop-shadow-md hidden sm:block ${className || ''}`}
        style={{ textShadow: '1px 1px 0px #3f3f3f' }}
      >
        {splashText}
      </motion.span>
    </AnimatePresence>
  );
};
export default SplashText;
