const base = {
  fontFamily:
    '"IBM Plex Mono", "JetBrains Mono", Consolas, Monaco, monospace',
  textAlign: 'left',
  whiteSpace: 'pre',
  wordSpacing: 'normal',
  wordBreak: 'normal',
  wordWrap: 'normal',
  lineHeight: '1.55',
  MozTabSize: '4',
  OTabSize: '4',
  tabSize: '4',
  WebkitHyphens: 'none',
  MozHyphens: 'none',
  msHyphens: 'none',
  hyphens: 'none',
};

export const galleyTheme = {
  'code[class*="language-"]': {
    ...base,
    color: '#1A1613',
    background: 'none',
    fontSize: '0.92em',
  },
  'pre[class*="language-"]': {
    ...base,
    color: '#1A1613',
    background: '#EDE3D2',
    padding: '1em',
    margin: '0.5em 0',
    overflow: 'auto',
    fontSize: '0.92em',
  },
  'pre[class*="language-"]::selection': {
    background: 'rgba(201,100,66,0.25)',
  },
  'code[class*="language-"]::selection': {
    background: 'rgba(201,100,66,0.25)',
  },
  ':not(pre) > code[class*="language-"]': {
    color: '#9E4A2F',
    background: 'rgba(201,100,66,0.08)',
    padding: '0.12em 0.35em',
    borderRadius: '2px',
  },
  comment: { color: '#7A6E5E', fontStyle: 'italic' },
  prolog: { color: '#7A6E5E', fontStyle: 'italic' },
  doctype: { color: '#7A6E5E', fontStyle: 'italic' },
  cdata: { color: '#7A6E5E', fontStyle: 'italic' },
  punctuation: { color: '#3A302A' },
  namespace: { opacity: '0.7' },
  property: { color: '#8A4A1B' },
  tag: { color: '#8A4A1B' },
  boolean: { color: '#8A4A1B' },
  number: { color: '#8A4A1B' },
  constant: { color: '#8A4A1B' },
  symbol: { color: '#8A4A1B' },
  deleted: { color: '#8A4A1B' },
  selector: { color: '#5F6F3E' },
  'attr-name': { color: '#5F6F3E' },
  string: { color: '#5F6F3E' },
  char: { color: '#5F6F3E' },
  builtin: { color: '#5F6F3E' },
  inserted: { color: '#5F6F3E' },
  operator: { color: '#9E4A2F' },
  entity: { color: '#9E4A2F', cursor: 'help' },
  url: { color: '#9E4A2F' },
  '.language-css .token.string': { color: '#9E4A2F' },
  '.style .token.string': { color: '#9E4A2F' },
  atrule: { color: '#6B4AA0' },
  'attr-value': { color: '#5F6F3E' },
  keyword: { color: '#6B4AA0', fontWeight: '600' },
  function: { color: '#3E5F8A', fontWeight: '600' },
  'class-name': { color: '#8A4A1B', fontWeight: '600' },
  regex: { color: '#6B4AA0' },
  important: { color: '#9E4A2F', fontWeight: 'bold' },
  variable: { color: '#1A1613' },
  bold: { fontWeight: 'bold' },
  italic: { fontStyle: 'italic' },
};
